language: node_js
node_js:
  - 0.4
  - 0.6
  - 0.7
before_install:
  - sudo apt-get update
  - sudo apt-get install php-pear
  - sudo pear upgrade PEAR
  - sudo pear channel-discover pear.phpunit.de
  - sudo pear channel-discover pear.symfony-project.com
  - sudo pear install --alldeps phpunit/PHPUnit
  - sudo apt-get install perl
  - sudo cpan install JSON
  - sudo cpan install List::MoreUtils
script: "make test"
