before_install:
  - sudo apt-get update
  - sudo apt-get install php-pear
  - sudo pear upgrade PEAR
  - sudo pear channel-discover pear.phpunit.de
  - sudo pear channel-discover pear.symfony-project.com
  - sudo pear install --alldeps phpunit/PHPUnit
  - sudo apt-get install cpanminus
  - sudo cpanm JSON::XS
  - sudo cpanm JSON
  - sudo cpanm List::MoreUtils
script: "make test"
